import Head from 'next/head'
import Header from '@/Components/Header'
import TableCards from '@/Components/TableCards'
import BarChart from '@/Components/BarChart'
import Apprehensions from '@/Components/Apprehensions'



export default function Home() {
  return (
    <>
      <Head>
        <title>Nordstrom Store Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <TableCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <Apprehensions />
        </div>
      </main>
    </>
  )
}
